### PR TITLE
Adding TPM check

### PR DESCRIPTION
**Pull request by ghost**
Automated GRUB/TPM check which should handle everything and warn the user accordingly.

### CODE REVIEW

**Comment by hirak99** [comment]
Thanks, nice patch.

**Comment by hirak99** [comment]
I made some changes, to make it a bit more robust - most of which are minor in commit d8e953a8ef5922816c84bb4d103a2bb138c6ab7c.

One of them however can be important -

The change 's/blacklist=tpm //g' would convert -

```
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash plymouth.ignore-serial-consoles tsc=directsync module_blacklist=tpm log_buf_len=4M amd_iommu=off amdgpu.gttsize=8128 spi_amd.speed_dev=1 audit=0 fbcon=vc:4-6 fbcon=rotate:1"
```

Into -
```
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash plymouth.ignore-serial-consoles tsc=directsync module_log_buf_len=4M amd_iommu=off amdgpu.gttsize=8128 spi_amd.speed_dev=1 audit=0 fbcon=vc:4-6 fbcon=rotate:1"
```

Notice `log_buf_len=4M` becomes `module_log_buf_len=4M`, which you do not want. If you used the script as you committed, you may want to correct it. All you need to do is to remove the `module_...` prefix.

**Comment by ghost** [comment]
Good catch, the script on my Deck was already corrected, so I must have forgotten to change that in the commit, my apologies!

**Comment by hirak99** [comment]
All good... thank you!

**Pull request merged**
